version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_228
    - 4.2.0_229
    - 4.2.0_231
    - 4.2.0_235
    - 4.2.0_238
    - 4.2.0_240
    - 4.2.0_241
    - 4.2.0_242
    - 4.2.0_245
    - 4.2.0_246
    - 4.2.0_247
    - 4.2.1_260
    - 4.2.1_261
  - dependency-name: com.sedmelluq:lavaplayer
    versions:
    - 1.3.66
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: org.mariadb.jdbc:mariadb-java-client
    versions:
    - 2.7.1
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.16
