language: java

jdk:
  - oraclejdk11
  - oraclejdk15
  - openjdk11
  - openjdk15

jobs:
  include:
    - stage: deploy
      jdk: openjdk11
      script: skip
      before_deploy:
        - ./gradlew beforeDeploy
      deploy:
        - provider: releases
          edge: true
          file_glob: true
          file: build/libs/*
          draft: true
          on:
            tags: true