language: java

jdk:
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

jobs:
  include:
    - stage: deploy
      jdk: openjdk11
      script: skip
      before_deploy:
        - ./gradlew shadowJar
      deploy:
        - provider: releases
          edge: true
          file_glob: true
          file: build/libs/*
          draft: true
          on:
            tags: true